ezpublish:
    siteaccess:
        default_siteaccess: eng
        list:
            - ez5_site
            - eng
            - nor
            - pol
            - ez5_site_admin
        groups:
            ezwebin_site_group:
                - ez5_site
                - eng
                - nor
                - pol
                - ez5_site_admin
        match:
            Map\Host:
                ez5: ez5_site
                admin.ez5: ez5_site_admin    
    system:
        ezwebin_site_group:
            database:
                type: mysql
                user: root
                password: root
                server: localhost
                database_name: ez5db
            var_dir: var/ezwebin_site
        eng:
            legacy_mode: true
            languages:
                - eng-GB
            image_variations:
                small:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 160] }
                medium:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 290] }
                listitem:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [130, 190] }
                articleimage:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [170, 350] }
                articlethumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [70, 150] }
                gallerythumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [105, 100] }
                galleryline:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [70, 150] }
                imagelarge:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [550, 730] }
                large:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [360, 440] }
                rss:
                    reference: null
                    filters:
                        - { name: geometry/scale, params: [88, 31] }
                logo:
                    reference: null
                    filters:
                        - { name: geometry/scaleheight, params: [36] }
                infoboximage:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [75] }
                billboard:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [764] }
                multiuploadthumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 80] }
            session_name: eZSESSID
        ez5_site_admin:
            legacy_mode: true
            languages:
                - eng-GB
                - nor-NO
                - pol-PL
            image_variations:
                reference:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [600, 600] }
                small:
                    reference: reference
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 100] }
                tiny:
                    reference: reference
                    filters:
                        - { name: geometry/scaledownonly, params: [30, 30] }
                medium:
                    reference: reference
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 200] }
                large:
                    reference: reference
                    filters:
                        - { name: geometry/scaledownonly, params: [300, 300] }
                rss:
                    reference: reference
                    filters:
                        - { name: geometry/scale, params: [88, 31] }
                multiuploadthumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 80] }
        ez5_site:
            legacy_mode: false
            languages:
                - eng-GB
                - nor-NO
                - pol-PL
            image_variations:
                small:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 160] }
                medium:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 290] }
                listitem:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [130, 190] }
                articleimage:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [170, 350] }
                articlethumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [70, 150] }
                gallerythumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [105, 100] }
                galleryline:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [70, 150] }
                imagelarge:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [550, 730] }
                large:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [360, 440] }
                rss:
                    reference: null
                    filters:
                        - { name: geometry/scale, params: [88, 31] }
                logo:
                    reference: null
                    filters:
                        - { name: geometry/scaleheight, params: [36] }
                infoboximage:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [75] }
                billboard:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [764] }
                multiuploadthumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 80] }
            session_name: eZSESSID
        nor:
            legacy_mode: true
            languages:
                - nor-NO
                - eng-GB
            image_variations:
                small:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 160] }
                medium:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 290] }
                listitem:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [130, 190] }
                articleimage:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [170, 350] }
                articlethumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [70, 150] }
                gallerythumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [105, 100] }
                galleryline:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [70, 150] }
                imagelarge:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [550, 730] }
                large:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [360, 440] }
                rss:
                    reference: null
                    filters:
                        - { name: geometry/scale, params: [88, 31] }
                logo:
                    reference: null
                    filters:
                        - { name: geometry/scaleheight, params: [36] }
                infoboximage:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [75] }
                billboard:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [764] }
                multiuploadthumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 80] }
            session_name: eZSESSID
        pol:
            legacy_mode: true
            languages:
                - pol-PL
                - eng-GB
            image_variations:
                small:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 160] }
                medium:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 290] }
                listitem:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [130, 190] }
                articleimage:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [170, 350] }
                articlethumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [70, 150] }
                gallerythumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [105, 100] }
                galleryline:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [70, 150] }
                imagelarge:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [550, 730] }
                large:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [360, 440] }
                rss:
                    reference: null
                    filters:
                        - { name: geometry/scale, params: [88, 31] }
                logo:
                    reference: null
                    filters:
                        - { name: geometry/scaleheight, params: [36] }
                infoboximage:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [75] }
                billboard:
                    reference: null
                    filters:
                        - { name: geometry/scalewidth, params: [764] }
                multiuploadthumbnail:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 80] }
            session_name: eZSESSID
    imagemagick:
        enabled: true
        path: /usr/bin/convert
        filters:
            geometry/scale: '-geometry {1}x{2}'
            geometry/scalewidth: '-geometry {1}'
            geometry/scaleheight: '-geometry x{1}'
            geometry/scaledownonly: '-geometry {1}x{2}>'
            geometry/scalewidthdownonly: '-geometry {1}>'
            geometry/scaleheightdownonly: '-geometry x{1}>'
            geometry/scaleexact: '-geometry {1}x{2}!'
            geometry/scalepercent: '-geometry {1}x{2}%'
            geometry/crop: '-crop {1}x{2}+{3}+{4}'
            filter/noise: '-noise {1}'
            filter/swirl: '-swirl {1}'
            colorspace/gray: '-colorspace GRAY'
            colorspace/transparent: '-colorspace Transparent'
            colorspace: '-colorspace {1}'
            border: '-border {1}x{2}'
            border/color: '-bordercolor rgb({1},{2},{3})'
            border/width: '-borderwidth {1}'
            flatten: -flatten
            resize: '-resize {1}'
    http_cache:
        purge_type: local
stash:
    caches:
        default:
            handlers:
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false
